package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccountitem<M extends BaseAccountitem<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long Id) {
		set("Id", Id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("Id");
	}

	/**
	 * 表头Id
	 */
	public void setHeaderId(java.lang.Long HeaderId) {
		set("HeaderId", HeaderId);
	}
	
	/**
	 * 表头Id
	 */
	public java.lang.Long getHeaderId() {
		return getLong("HeaderId");
	}

	/**
	 * 账户Id
	 */
	public void setAccountId(java.lang.Long AccountId) {
		set("AccountId", AccountId);
	}
	
	/**
	 * 账户Id
	 */
	public java.lang.Long getAccountId() {
		return getLong("AccountId");
	}

	/**
	 * 收支项目Id
	 */
	public void setInOutItemId(java.lang.Long InOutItemId) {
		set("InOutItemId", InOutItemId);
	}
	
	/**
	 * 收支项目Id
	 */
	public java.lang.Long getInOutItemId() {
		return getLong("InOutItemId");
	}

	/**
	 * 单项金额
	 */
	public void setEachAmount(java.math.BigDecimal EachAmount) {
		set("EachAmount", EachAmount);
	}
	
	/**
	 * 单项金额
	 */
	public java.math.BigDecimal getEachAmount() {
		return get("EachAmount");
	}

	/**
	 * 单据备注
	 */
	public void setRemark(java.lang.String Remark) {
		set("Remark", Remark);
	}
	
	/**
	 * 单据备注
	 */
	public java.lang.String getRemark() {
		return getStr("Remark");
	}

	/**
	 * 租户id
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 租户id
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}

	/**
	 * 删除标记，0未删除，1删除
	 */
	public void setDeleteFlag(java.lang.String deleteFlag) {
		set("delete_Flag", deleteFlag);
	}
	
	/**
	 * 删除标记，0未删除，1删除
	 */
	public java.lang.String getDeleteFlag() {
		return getStr("delete_Flag");
	}

}
