package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDepotitem<M extends BaseDepotitem<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long Id) {
		set("Id", Id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("Id");
	}

	/**
	 * 表头Id
	 */
	public void setHeaderId(java.lang.Long HeaderId) {
		set("HeaderId", HeaderId);
	}
	
	/**
	 * 表头Id
	 */
	public java.lang.Long getHeaderId() {
		return getLong("HeaderId");
	}

	/**
	 * 材料Id
	 */
	public void setMaterialId(java.lang.Long MaterialId) {
		set("MaterialId", MaterialId);
	}
	
	/**
	 * 材料Id
	 */
	public java.lang.Long getMaterialId() {
		return getLong("MaterialId");
	}

	/**
	 * 商品计量单位
	 */
	public void setMUnit(java.lang.String MUnit) {
		set("MUnit", MUnit);
	}
	
	/**
	 * 商品计量单位
	 */
	public java.lang.String getMUnit() {
		return getStr("MUnit");
	}

	/**
	 * 数量
	 */
	public void setOperNumber(java.math.BigDecimal OperNumber) {
		set("OperNumber", OperNumber);
	}
	
	/**
	 * 数量
	 */
	public java.math.BigDecimal getOperNumber() {
		return get("OperNumber");
	}

	/**
	 * 基础数量，如kg、瓶
	 */
	public void setBasicNumber(java.math.BigDecimal BasicNumber) {
		set("BasicNumber", BasicNumber);
	}
	
	/**
	 * 基础数量，如kg、瓶
	 */
	public java.math.BigDecimal getBasicNumber() {
		return get("BasicNumber");
	}

	/**
	 * 单价
	 */
	public void setUnitPrice(java.math.BigDecimal UnitPrice) {
		set("UnitPrice", UnitPrice);
	}
	
	/**
	 * 单价
	 */
	public java.math.BigDecimal getUnitPrice() {
		return get("UnitPrice");
	}

	/**
	 * 含税单价
	 */
	public void setTaxUnitPrice(java.math.BigDecimal TaxUnitPrice) {
		set("TaxUnitPrice", TaxUnitPrice);
	}
	
	/**
	 * 含税单价
	 */
	public java.math.BigDecimal getTaxUnitPrice() {
		return get("TaxUnitPrice");
	}

	/**
	 * 金额
	 */
	public void setAllPrice(java.math.BigDecimal AllPrice) {
		set("AllPrice", AllPrice);
	}
	
	/**
	 * 金额
	 */
	public java.math.BigDecimal getAllPrice() {
		return get("AllPrice");
	}

	/**
	 * 描述
	 */
	public void setRemark(java.lang.String Remark) {
		set("Remark", Remark);
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getRemark() {
		return getStr("Remark");
	}

	/**
	 * 图片
	 */
	public void setImg(java.lang.String Img) {
		set("Img", Img);
	}
	
	/**
	 * 图片
	 */
	public java.lang.String getImg() {
		return getStr("Img");
	}

	/**
	 * 运杂费
	 */
	public void setIncidentals(java.math.BigDecimal Incidentals) {
		set("Incidentals", Incidentals);
	}
	
	/**
	 * 运杂费
	 */
	public java.math.BigDecimal getIncidentals() {
		return get("Incidentals");
	}

	/**
	 * 仓库ID（库存是统计出来的）
	 */
	public void setDepotId(java.lang.Long DepotId) {
		set("DepotId", DepotId);
	}
	
	/**
	 * 仓库ID（库存是统计出来的）
	 */
	public java.lang.Long getDepotId() {
		return getLong("DepotId");
	}

	/**
	 * 调拨时，对方仓库Id
	 */
	public void setAnotherDepotId(java.lang.Long AnotherDepotId) {
		set("AnotherDepotId", AnotherDepotId);
	}
	
	/**
	 * 调拨时，对方仓库Id
	 */
	public java.lang.Long getAnotherDepotId() {
		return getLong("AnotherDepotId");
	}

	/**
	 * 税率
	 */
	public void setTaxRate(java.math.BigDecimal TaxRate) {
		set("TaxRate", TaxRate);
	}
	
	/**
	 * 税率
	 */
	public java.math.BigDecimal getTaxRate() {
		return get("TaxRate");
	}

	/**
	 * 税额
	 */
	public void setTaxMoney(java.math.BigDecimal TaxMoney) {
		set("TaxMoney", TaxMoney);
	}
	
	/**
	 * 税额
	 */
	public java.math.BigDecimal getTaxMoney() {
		return get("TaxMoney");
	}

	/**
	 * 价税合计
	 */
	public void setTaxLastMoney(java.math.BigDecimal TaxLastMoney) {
		set("TaxLastMoney", TaxLastMoney);
	}
	
	/**
	 * 价税合计
	 */
	public java.math.BigDecimal getTaxLastMoney() {
		return get("TaxLastMoney");
	}

	/**
	 * 自定义字段1-品名
	 */
	public void setOtherField1(java.lang.String OtherField1) {
		set("OtherField1", OtherField1);
	}
	
	/**
	 * 自定义字段1-品名
	 */
	public java.lang.String getOtherField1() {
		return getStr("OtherField1");
	}

	/**
	 * 自定义字段2-型号
	 */
	public void setOtherField2(java.lang.String OtherField2) {
		set("OtherField2", OtherField2);
	}
	
	/**
	 * 自定义字段2-型号
	 */
	public java.lang.String getOtherField2() {
		return getStr("OtherField2");
	}

	/**
	 * 自定义字段3-制造商
	 */
	public void setOtherField3(java.lang.String OtherField3) {
		set("OtherField3", OtherField3);
	}
	
	/**
	 * 自定义字段3-制造商
	 */
	public java.lang.String getOtherField3() {
		return getStr("OtherField3");
	}

	/**
	 * 自定义字段4
	 */
	public void setOtherField4(java.lang.String OtherField4) {
		set("OtherField4", OtherField4);
	}
	
	/**
	 * 自定义字段4
	 */
	public java.lang.String getOtherField4() {
		return getStr("OtherField4");
	}

	/**
	 * 自定义字段5
	 */
	public void setOtherField5(java.lang.String OtherField5) {
		set("OtherField5", OtherField5);
	}
	
	/**
	 * 自定义字段5
	 */
	public java.lang.String getOtherField5() {
		return getStr("OtherField5");
	}

	/**
	 * 商品类型
	 */
	public void setMType(java.lang.String MType) {
		set("MType", MType);
	}
	
	/**
	 * 商品类型
	 */
	public java.lang.String getMType() {
		return getStr("MType");
	}

	/**
	 * 租户id
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 租户id
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}

	/**
	 * 删除标记，0未删除，1删除
	 */
	public void setDeleteFlag(java.lang.String deleteFlag) {
		set("delete_Flag", deleteFlag);
	}
	
	/**
	 * 删除标记，0未删除，1删除
	 */
	public java.lang.String getDeleteFlag() {
		return getStr("delete_Flag");
	}

}
