package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFunctions<M extends BaseFunctions<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long Id) {
		set("Id", Id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("Id");
	}

	/**
	 * 编号
	 */
	public void setNumber(java.lang.String Number) {
		set("Number", Number);
	}
	
	/**
	 * 编号
	 */
	public java.lang.String getNumber() {
		return getStr("Number");
	}

	/**
	 * 名称
	 */
	public void setName(java.lang.String Name) {
		set("Name", Name);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("Name");
	}

	/**
	 * 上级编号
	 */
	public void setPNumber(java.lang.String PNumber) {
		set("PNumber", PNumber);
	}
	
	/**
	 * 上级编号
	 */
	public java.lang.String getPNumber() {
		return getStr("PNumber");
	}

	/**
	 * 链接
	 */
	public void setURL(java.lang.String URL) {
		set("URL", URL);
	}
	
	/**
	 * 链接
	 */
	public java.lang.String getURL() {
		return getStr("URL");
	}

	/**
	 * 收缩
	 */
	public void setState(java.lang.Boolean State) {
		set("State", State);
	}
	
	/**
	 * 收缩
	 */
	public java.lang.Boolean getState() {
		return get("State");
	}

	/**
	 * 排序
	 */
	public void setSort(java.lang.String Sort) {
		set("Sort", Sort);
	}
	
	/**
	 * 排序
	 */
	public java.lang.String getSort() {
		return getStr("Sort");
	}

	/**
	 * 启用
	 */
	public void setEnabled(java.lang.Boolean Enabled) {
		set("Enabled", Enabled);
	}
	
	/**
	 * 启用
	 */
	public java.lang.Boolean getEnabled() {
		return get("Enabled");
	}

	/**
	 * 类型
	 */
	public void setType(java.lang.String Type) {
		set("Type", Type);
	}
	
	/**
	 * 类型
	 */
	public java.lang.String getType() {
		return getStr("Type");
	}

	/**
	 * 功能按钮
	 */
	public void setPushBtn(java.lang.String PushBtn) {
		set("PushBtn", PushBtn);
	}
	
	/**
	 * 功能按钮
	 */
	public java.lang.String getPushBtn() {
		return getStr("PushBtn");
	}

	/**
	 * 图标
	 */
	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	/**
	 * 图标
	 */
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	/**
	 * 删除标记，0未删除，1删除
	 */
	public void setDeleteFlag(java.lang.String deleteFlag) {
		set("delete_Flag", deleteFlag);
	}
	
	/**
	 * 删除标记，0未删除，1删除
	 */
	public java.lang.String getDeleteFlag() {
		return getStr("delete_Flag");
	}

}
