package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccounthead<M extends BaseAccounthead<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long Id) {
		set("Id", Id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("Id");
	}

	/**
	 * 类型(支出/收入/收款/付款/转账)
	 */
	public void setType(java.lang.String Type) {
		set("Type", Type);
	}
	
	/**
	 * 类型(支出/收入/收款/付款/转账)
	 */
	public java.lang.String getType() {
		return getStr("Type");
	}

	/**
	 * 单位Id(收款/付款单位)
	 */
	public void setOrganId(java.lang.Long OrganId) {
		set("OrganId", OrganId);
	}
	
	/**
	 * 单位Id(收款/付款单位)
	 */
	public java.lang.Long getOrganId() {
		return getLong("OrganId");
	}

	/**
	 * 经手人Id
	 */
	public void setHandsPersonId(java.lang.Long HandsPersonId) {
		set("HandsPersonId", HandsPersonId);
	}
	
	/**
	 * 经手人Id
	 */
	public java.lang.Long getHandsPersonId() {
		return getLong("HandsPersonId");
	}

	/**
	 * 变动金额(优惠/收款/付款/实付)
	 */
	public void setChangeAmount(java.math.BigDecimal ChangeAmount) {
		set("ChangeAmount", ChangeAmount);
	}
	
	/**
	 * 变动金额(优惠/收款/付款/实付)
	 */
	public java.math.BigDecimal getChangeAmount() {
		return get("ChangeAmount");
	}

	/**
	 * 合计金额
	 */
	public void setTotalPrice(java.math.BigDecimal TotalPrice) {
		set("TotalPrice", TotalPrice);
	}
	
	/**
	 * 合计金额
	 */
	public java.math.BigDecimal getTotalPrice() {
		return get("TotalPrice");
	}

	/**
	 * 账户(收款/付款)
	 */
	public void setAccountId(java.lang.Long AccountId) {
		set("AccountId", AccountId);
	}
	
	/**
	 * 账户(收款/付款)
	 */
	public java.lang.Long getAccountId() {
		return getLong("AccountId");
	}

	/**
	 * 单据编号
	 */
	public void setBillNo(java.lang.String BillNo) {
		set("BillNo", BillNo);
	}
	
	/**
	 * 单据编号
	 */
	public java.lang.String getBillNo() {
		return getStr("BillNo");
	}

	/**
	 * 单据日期
	 */
	public void setBillTime(java.util.Date BillTime) {
		set("BillTime", BillTime);
	}
	
	/**
	 * 单据日期
	 */
	public java.util.Date getBillTime() {
		return get("BillTime");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String Remark) {
		set("Remark", Remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("Remark");
	}

	/**
	 * 租户id
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 租户id
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}

	/**
	 * 删除标记，0未删除，1删除
	 */
	public void setDeleteFlag(java.lang.String deleteFlag) {
		set("delete_Flag", deleteFlag);
	}
	
	/**
	 * 删除标记，0未删除，1删除
	 */
	public java.lang.String getDeleteFlag() {
		return getStr("delete_Flag");
	}

}
