package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDepothead<M extends BaseDepothead<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long Id) {
		set("Id", Id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("Id");
	}

	/**
	 * 类型(出库/入库)
	 */
	public void setType(java.lang.String Type) {
		set("Type", Type);
	}
	
	/**
	 * 类型(出库/入库)
	 */
	public java.lang.String getType() {
		return getStr("Type");
	}

	/**
	 * 出入库分类
	 */
	public void setSubType(java.lang.String SubType) {
		set("SubType", SubType);
	}
	
	/**
	 * 出入库分类
	 */
	public java.lang.String getSubType() {
		return getStr("SubType");
	}

	/**
	 * 项目Id
	 */
	public void setProjectId(java.lang.Long ProjectId) {
		set("ProjectId", ProjectId);
	}
	
	/**
	 * 项目Id
	 */
	public java.lang.Long getProjectId() {
		return getLong("ProjectId");
	}

	/**
	 * 初始票据号
	 */
	public void setDefaultNumber(java.lang.String DefaultNumber) {
		set("DefaultNumber", DefaultNumber);
	}
	
	/**
	 * 初始票据号
	 */
	public java.lang.String getDefaultNumber() {
		return getStr("DefaultNumber");
	}

	/**
	 * 票据号
	 */
	public void setNumber(java.lang.String Number) {
		set("Number", Number);
	}
	
	/**
	 * 票据号
	 */
	public java.lang.String getNumber() {
		return getStr("Number");
	}

	/**
	 * 操作员名字
	 */
	public void setOperPersonName(java.lang.String OperPersonName) {
		set("OperPersonName", OperPersonName);
	}
	
	/**
	 * 操作员名字
	 */
	public java.lang.String getOperPersonName() {
		return getStr("OperPersonName");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date CreateTime) {
		set("CreateTime", CreateTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("CreateTime");
	}

	/**
	 * 出入库时间
	 */
	public void setOperTime(java.util.Date OperTime) {
		set("OperTime", OperTime);
	}
	
	/**
	 * 出入库时间
	 */
	public java.util.Date getOperTime() {
		return get("OperTime");
	}

	/**
	 * 供应商Id
	 */
	public void setOrganId(java.lang.Long OrganId) {
		set("OrganId", OrganId);
	}
	
	/**
	 * 供应商Id
	 */
	public java.lang.Long getOrganId() {
		return getLong("OrganId");
	}

	/**
	 * 采购/领料-经手人Id
	 */
	public void setHandsPersonId(java.lang.Long HandsPersonId) {
		set("HandsPersonId", HandsPersonId);
	}
	
	/**
	 * 采购/领料-经手人Id
	 */
	public java.lang.Long getHandsPersonId() {
		return getLong("HandsPersonId");
	}

	/**
	 * 账户Id
	 */
	public void setAccountId(java.lang.Long AccountId) {
		set("AccountId", AccountId);
	}
	
	/**
	 * 账户Id
	 */
	public java.lang.Long getAccountId() {
		return getLong("AccountId");
	}

	/**
	 * 变动金额(收款/付款)
	 */
	public void setChangeAmount(java.math.BigDecimal ChangeAmount) {
		set("ChangeAmount", ChangeAmount);
	}
	
	/**
	 * 变动金额(收款/付款)
	 */
	public java.math.BigDecimal getChangeAmount() {
		return get("ChangeAmount");
	}

	/**
	 * 调拨时，对方项目Id
	 */
	public void setAllocationProjectId(java.lang.Long AllocationProjectId) {
		set("AllocationProjectId", AllocationProjectId);
	}
	
	/**
	 * 调拨时，对方项目Id
	 */
	public java.lang.Long getAllocationProjectId() {
		return getLong("AllocationProjectId");
	}

	/**
	 * 合计金额
	 */
	public void setTotalPrice(java.math.BigDecimal TotalPrice) {
		set("TotalPrice", TotalPrice);
	}
	
	/**
	 * 合计金额
	 */
	public java.math.BigDecimal getTotalPrice() {
		return get("TotalPrice");
	}

	/**
	 * 付款类型(现金、记账等)
	 */
	public void setPayType(java.lang.String PayType) {
		set("PayType", PayType);
	}
	
	/**
	 * 付款类型(现金、记账等)
	 */
	public java.lang.String getPayType() {
		return getStr("PayType");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String Remark) {
		set("Remark", Remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("Remark");
	}

	/**
	 * 业务员（可以多个）
	 */
	public void setSalesman(java.lang.String Salesman) {
		set("Salesman", Salesman);
	}
	
	/**
	 * 业务员（可以多个）
	 */
	public java.lang.String getSalesman() {
		return getStr("Salesman");
	}

	/**
	 * 多账户ID列表
	 */
	public void setAccountIdList(java.lang.String AccountIdList) {
		set("AccountIdList", AccountIdList);
	}
	
	/**
	 * 多账户ID列表
	 */
	public java.lang.String getAccountIdList() {
		return getStr("AccountIdList");
	}

	/**
	 * 多账户金额列表
	 */
	public void setAccountMoneyList(java.lang.String AccountMoneyList) {
		set("AccountMoneyList", AccountMoneyList);
	}
	
	/**
	 * 多账户金额列表
	 */
	public java.lang.String getAccountMoneyList() {
		return getStr("AccountMoneyList");
	}

	/**
	 * 优惠率
	 */
	public void setDiscount(java.math.BigDecimal Discount) {
		set("Discount", Discount);
	}
	
	/**
	 * 优惠率
	 */
	public java.math.BigDecimal getDiscount() {
		return get("Discount");
	}

	/**
	 * 优惠金额
	 */
	public void setDiscountMoney(java.math.BigDecimal DiscountMoney) {
		set("DiscountMoney", DiscountMoney);
	}
	
	/**
	 * 优惠金额
	 */
	public java.math.BigDecimal getDiscountMoney() {
		return get("DiscountMoney");
	}

	/**
	 * 优惠后金额
	 */
	public void setDiscountLastMoney(java.math.BigDecimal DiscountLastMoney) {
		set("DiscountLastMoney", DiscountLastMoney);
	}
	
	/**
	 * 优惠后金额
	 */
	public java.math.BigDecimal getDiscountLastMoney() {
		return get("DiscountLastMoney");
	}

	/**
	 * 销售或采购费用合计
	 */
	public void setOtherMoney(java.math.BigDecimal OtherMoney) {
		set("OtherMoney", OtherMoney);
	}
	
	/**
	 * 销售或采购费用合计
	 */
	public java.math.BigDecimal getOtherMoney() {
		return get("OtherMoney");
	}

	/**
	 * 销售或采购费用涉及项目Id数组（包括快递、招待等）
	 */
	public void setOtherMoneyList(java.lang.String OtherMoneyList) {
		set("OtherMoneyList", OtherMoneyList);
	}
	
	/**
	 * 销售或采购费用涉及项目Id数组（包括快递、招待等）
	 */
	public java.lang.String getOtherMoneyList() {
		return getStr("OtherMoneyList");
	}

	/**
	 * 销售或采购费用涉及项目（包括快递、招待等）
	 */
	public void setOtherMoneyItem(java.lang.String OtherMoneyItem) {
		set("OtherMoneyItem", OtherMoneyItem);
	}
	
	/**
	 * 销售或采购费用涉及项目（包括快递、招待等）
	 */
	public java.lang.String getOtherMoneyItem() {
		return getStr("OtherMoneyItem");
	}

	/**
	 * 结算天数
	 */
	public void setAccountDay(java.lang.Integer AccountDay) {
		set("AccountDay", AccountDay);
	}
	
	/**
	 * 结算天数
	 */
	public java.lang.Integer getAccountDay() {
		return getInt("AccountDay");
	}

	/**
	 * 状态，0未审核、1已审核、2已转采购|销售
	 */
	public void setStatus(java.lang.String Status) {
		set("Status", Status);
	}
	
	/**
	 * 状态，0未审核、1已审核、2已转采购|销售
	 */
	public java.lang.String getStatus() {
		return getStr("Status");
	}

	/**
	 * 关联订单号
	 */
	public void setLinkNumber(java.lang.String LinkNumber) {
		set("LinkNumber", LinkNumber);
	}
	
	/**
	 * 关联订单号
	 */
	public java.lang.String getLinkNumber() {
		return getStr("LinkNumber");
	}

	/**
	 * 租户id
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 租户id
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}

	/**
	 * 删除标记，0未删除，1删除
	 */
	public void setDeleteFlag(java.lang.String deleteFlag) {
		set("delete_Flag", deleteFlag);
	}
	
	/**
	 * 删除标记，0未删除，1删除
	 */
	public java.lang.String getDeleteFlag() {
		return getStr("delete_Flag");
	}

}
