package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrgaUserRel<M extends BaseOrgaUserRel<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 机构id
	 */
	public void setOrgaId(java.lang.Long orgaId) {
		set("orga_id", orgaId);
	}
	
	/**
	 * 机构id
	 */
	public java.lang.Long getOrgaId() {
		return getLong("orga_id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	/**
	 * 用户在所属机构中显示顺序
	 */
	public void setUserBlngOrgaDsplSeq(java.lang.String userBlngOrgaDsplSeq) {
		set("user_blng_orga_dspl_seq", userBlngOrgaDsplSeq);
	}
	
	/**
	 * 用户在所属机构中显示顺序
	 */
	public java.lang.String getUserBlngOrgaDsplSeq() {
		return getStr("user_blng_orga_dspl_seq");
	}

	/**
	 * 删除标记，0未删除，1删除
	 */
	public void setDeleteFlag(java.lang.String deleteFlag) {
		set("delete_flag", deleteFlag);
	}
	
	/**
	 * 删除标记，0未删除，1删除
	 */
	public java.lang.String getDeleteFlag() {
		return getStr("delete_flag");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 创建人
	 */
	public void setCreator(java.lang.Long creator) {
		set("creator", creator);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.Long getCreator() {
		return getLong("creator");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 更新人
	 */
	public void setUpdater(java.lang.Long updater) {
		set("updater", updater);
	}
	
	/**
	 * 更新人
	 */
	public java.lang.Long getUpdater() {
		return getLong("updater");
	}

	/**
	 * 租户id
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 租户id
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}

}
