package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSerialNumber<M extends BaseSerialNumber<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 产品表id
	 */
	public void setMaterialId(java.lang.Long materialId) {
		set("material_Id", materialId);
	}
	
	/**
	 * 产品表id
	 */
	public java.lang.Long getMaterialId() {
		return getLong("material_Id");
	}

	/**
	 * 序列号
	 */
	public void setSerialNumber(java.lang.String serialNumber) {
		set("serial_Number", serialNumber);
	}
	
	/**
	 * 序列号
	 */
	public java.lang.String getSerialNumber() {
		return getStr("serial_Number");
	}

	/**
	 * 是否卖出，0未卖出，1卖出
	 */
	public void setIsSell(java.lang.String isSell) {
		set("is_Sell", isSell);
	}
	
	/**
	 * 是否卖出，0未卖出，1卖出
	 */
	public java.lang.String getIsSell() {
		return getStr("is_Sell");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 删除标记，0未删除，1删除
	 */
	public void setDeleteFlag(java.lang.String deleteFlag) {
		set("delete_Flag", deleteFlag);
	}
	
	/**
	 * 删除标记，0未删除，1删除
	 */
	public java.lang.String getDeleteFlag() {
		return getStr("delete_Flag");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_Time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_Time");
	}

	/**
	 * 创建人
	 */
	public void setCreator(java.lang.Long creator) {
		set("creator", creator);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.Long getCreator() {
		return getLong("creator");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_Time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_Time");
	}

	/**
	 * 更新人
	 */
	public void setUpdater(java.lang.Long updater) {
		set("updater", updater);
	}
	
	/**
	 * 更新人
	 */
	public java.lang.Long getUpdater() {
		return getLong("updater");
	}

	/**
	 * 单据主表id，用于跟踪序列号流向
	 */
	public void setDepotheadId(java.lang.Long depotheadId) {
		set("depothead_Id", depotheadId);
	}
	
	/**
	 * 单据主表id，用于跟踪序列号流向
	 */
	public java.lang.Long getDepotheadId() {
		return getLong("depothead_Id");
	}

	/**
	 * 租户id
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 租户id
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}

}
