package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserbusiness<M extends BaseUserbusiness<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long Id) {
		set("Id", Id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("Id");
	}

	/**
	 * 类别
	 */
	public void setType(java.lang.String Type) {
		set("Type", Type);
	}
	
	/**
	 * 类别
	 */
	public java.lang.String getType() {
		return getStr("Type");
	}

	/**
	 * 主ID
	 */
	public void setKeyId(java.lang.String KeyId) {
		set("KeyId", KeyId);
	}
	
	/**
	 * 主ID
	 */
	public java.lang.String getKeyId() {
		return getStr("KeyId");
	}

	/**
	 * 值
	 */
	public void setValue(java.lang.String Value) {
		set("Value", Value);
	}
	
	/**
	 * 值
	 */
	public java.lang.String getValue() {
		return getStr("Value");
	}

	/**
	 * 按钮权限
	 */
	public void setBtnStr(java.lang.String BtnStr) {
		set("BtnStr", BtnStr);
	}
	
	/**
	 * 按钮权限
	 */
	public java.lang.String getBtnStr() {
		return getStr("BtnStr");
	}

	/**
	 * 删除标记，0未删除，1删除
	 */
	public void setDeleteFlag(java.lang.String deleteFlag) {
		set("delete_Flag", deleteFlag);
	}
	
	/**
	 * 删除标记，0未删除，1删除
	 */
	public java.lang.String getDeleteFlag() {
		return getStr("delete_Flag");
	}

}
