package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMaterialcategory<M extends BaseMaterialcategory<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long Id) {
		set("Id", Id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("Id");
	}

	/**
	 * 名称
	 */
	public void setName(java.lang.String Name) {
		set("Name", Name);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("Name");
	}

	/**
	 * 等级
	 */
	public void setCategoryLevel(java.lang.Integer CategoryLevel) {
		set("CategoryLevel", CategoryLevel);
	}
	
	/**
	 * 等级
	 */
	public java.lang.Integer getCategoryLevel() {
		return getInt("CategoryLevel");
	}

	/**
	 * 上级ID
	 */
	public void setParentId(java.lang.Long ParentId) {
		set("ParentId", ParentId);
	}
	
	/**
	 * 上级ID
	 */
	public java.lang.Long getParentId() {
		return getLong("ParentId");
	}

	/**
	 * 显示顺序
	 */
	public void setSort(java.lang.String sort) {
		set("sort", sort);
	}
	
	/**
	 * 显示顺序
	 */
	public java.lang.String getSort() {
		return getStr("sort");
	}

	/**
	 * 状态，0系统默认，1启用，2删除
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态，0系统默认，1启用，2删除
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}

	/**
	 * 编号
	 */
	public void setSerialNo(java.lang.String serialNo) {
		set("serial_no", serialNo);
	}
	
	/**
	 * 编号
	 */
	public java.lang.String getSerialNo() {
		return getStr("serial_no");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 创建人
	 */
	public void setCreator(java.lang.Long creator) {
		set("creator", creator);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.Long getCreator() {
		return getLong("creator");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 更新人
	 */
	public void setUpdater(java.lang.Long updater) {
		set("updater", updater);
	}
	
	/**
	 * 更新人
	 */
	public java.lang.Long getUpdater() {
		return getLong("updater");
	}

	/**
	 * 租户id
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 租户id
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}

}
