package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 用户姓名--例如张三
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	/**
	 * 用户姓名--例如张三
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * 登录用户名--可能为空
	 */
	public void setLoginame(java.lang.String loginame) {
		set("loginame", loginame);
	}
	
	/**
	 * 登录用户名--可能为空
	 */
	public java.lang.String getLoginame() {
		return getStr("loginame");
	}

	/**
	 * 登陆密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 登陆密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 职位
	 */
	public void setPosition(java.lang.String position) {
		set("position", position);
	}
	
	/**
	 * 职位
	 */
	public java.lang.String getPosition() {
		return getStr("position");
	}

	/**
	 * 所属部门
	 */
	public void setDepartment(java.lang.String department) {
		set("department", department);
	}
	
	/**
	 * 所属部门
	 */
	public java.lang.String getDepartment() {
		return getStr("department");
	}

	/**
	 * 电子邮箱
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 电子邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}

	/**
	 * 手机号码
	 */
	public void setPhonenum(java.lang.String phonenum) {
		set("phonenum", phonenum);
	}
	
	/**
	 * 手机号码
	 */
	public java.lang.String getPhonenum() {
		return getStr("phonenum");
	}

	/**
	 * 是否为管理者 0==管理者 1==员工
	 */
	public void setIsmanager(java.lang.Integer ismanager) {
		set("ismanager", ismanager);
	}
	
	/**
	 * 是否为管理者 0==管理者 1==员工
	 */
	public java.lang.Integer getIsmanager() {
		return getInt("ismanager");
	}

	/**
	 * 是否系统自带数据 
	 */
	public void setIsystem(java.lang.Integer isystem) {
		set("isystem", isystem);
	}
	
	/**
	 * 是否系统自带数据 
	 */
	public java.lang.Integer getIsystem() {
		return getInt("isystem");
	}

	/**
	 * 状态，0：正常，1：删除，2封禁
	 */
	public void setStatus(java.lang.Integer Status) {
		set("Status", Status);
	}
	
	/**
	 * 状态，0：正常，1：删除，2封禁
	 */
	public java.lang.Integer getStatus() {
		return getInt("Status");
	}

	/**
	 * 用户描述信息
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 用户描述信息
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 租户id
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 租户id
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}

}
