package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTenant<M extends BaseTenant<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 用户id
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}

	/**
	 * 登录名
	 */
	public void setLoginName(java.lang.String loginName) {
		set("login_name", loginName);
	}
	
	/**
	 * 登录名
	 */
	public java.lang.String getLoginName() {
		return getStr("login_name");
	}

	/**
	 * 用户数量限制
	 */
	public void setUserNumLimit(java.lang.Integer userNumLimit) {
		set("user_num_limit", userNumLimit);
	}
	
	/**
	 * 用户数量限制
	 */
	public java.lang.Integer getUserNumLimit() {
		return getInt("user_num_limit");
	}

	/**
	 * 单据数量限制
	 */
	public void setBillsNumLimit(java.lang.Integer billsNumLimit) {
		set("bills_num_limit", billsNumLimit);
	}
	
	/**
	 * 单据数量限制
	 */
	public java.lang.Integer getBillsNumLimit() {
		return getInt("bills_num_limit");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
