package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 操作用户ID
	 */
	public void setUserID(java.lang.Long userID) {
		set("userID", userID);
	}
	
	/**
	 * 操作用户ID
	 */
	public java.lang.Long getUserID() {
		return getLong("userID");
	}

	/**
	 * 操作模块名称
	 */
	public void setOperation(java.lang.String operation) {
		set("operation", operation);
	}
	
	/**
	 * 操作模块名称
	 */
	public java.lang.String getOperation() {
		return getStr("operation");
	}

	/**
	 * 客户端IP
	 */
	public void setClientIP(java.lang.String clientIP) {
		set("clientIP", clientIP);
	}
	
	/**
	 * 客户端IP
	 */
	public java.lang.String getClientIP() {
		return getStr("clientIP");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	/**
	 * 操作状态 0==成功，1==失败
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 操作状态 0==成功，1==失败
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 操作详情
	 */
	public void setContentdetails(java.lang.String contentdetails) {
		set("contentdetails", contentdetails);
	}
	
	/**
	 * 操作详情
	 */
	public java.lang.String getContentdetails() {
		return getStr("contentdetails");
	}

	/**
	 * 备注信息
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注信息
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 租户id
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 租户id
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}

}
