package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsg<M extends BaseMsg<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 消息标题
	 */
	public void setMsgTitle(java.lang.String msgTitle) {
		set("msg_title", msgTitle);
	}
	
	/**
	 * 消息标题
	 */
	public java.lang.String getMsgTitle() {
		return getStr("msg_title");
	}

	/**
	 * 消息内容
	 */
	public void setMsgContent(java.lang.String msgContent) {
		set("msg_content", msgContent);
	}
	
	/**
	 * 消息内容
	 */
	public java.lang.String getMsgContent() {
		return getStr("msg_content");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 消息类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 消息类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 状态，1未读 2已读
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态，1未读 2已读
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}

	/**
	 * 租户id
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 租户id
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}

	/**
	 * 删除标记，0未删除，1删除
	 */
	public void setDeleteFlag(java.lang.String deleteFlag) {
		set("delete_Flag", deleteFlag);
	}
	
	/**
	 * 删除标记，0未删除，1删除
	 */
	public java.lang.String getDeleteFlag() {
		return getStr("delete_Flag");
	}

}
