package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMaterial<M extends BaseMaterial<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long Id) {
		set("Id", Id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("Id");
	}

	/**
	 * 产品类型
	 */
	public void setCategoryId(java.lang.Long CategoryId) {
		set("CategoryId", CategoryId);
	}
	
	/**
	 * 产品类型
	 */
	public java.lang.Long getCategoryId() {
		return getLong("CategoryId");
	}

	/**
	 * 名称
	 */
	public void setName(java.lang.String Name) {
		set("Name", Name);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("Name");
	}

	/**
	 * 制造商
	 */
	public void setMfrs(java.lang.String Mfrs) {
		set("Mfrs", Mfrs);
	}
	
	/**
	 * 制造商
	 */
	public java.lang.String getMfrs() {
		return getStr("Mfrs");
	}

	/**
	 * 包装（KG/包）
	 */
	public void setPacking(java.math.BigDecimal Packing) {
		set("Packing", Packing);
	}
	
	/**
	 * 包装（KG/包）
	 */
	public java.math.BigDecimal getPacking() {
		return get("Packing");
	}

	/**
	 * 安全存量（KG）
	 */
	public void setSafetyStock(java.math.BigDecimal SafetyStock) {
		set("SafetyStock", SafetyStock);
	}
	
	/**
	 * 安全存量（KG）
	 */
	public java.math.BigDecimal getSafetyStock() {
		return get("SafetyStock");
	}

	/**
	 * 型号
	 */
	public void setModel(java.lang.String Model) {
		set("Model", Model);
	}
	
	/**
	 * 型号
	 */
	public java.lang.String getModel() {
		return getStr("Model");
	}

	/**
	 * 规格
	 */
	public void setStandard(java.lang.String Standard) {
		set("Standard", Standard);
	}
	
	/**
	 * 规格
	 */
	public java.lang.String getStandard() {
		return getStr("Standard");
	}

	/**
	 * 颜色
	 */
	public void setColor(java.lang.String Color) {
		set("Color", Color);
	}
	
	/**
	 * 颜色
	 */
	public java.lang.String getColor() {
		return getStr("Color");
	}

	/**
	 * 单位-单个
	 */
	public void setUnit(java.lang.String Unit) {
		set("Unit", Unit);
	}
	
	/**
	 * 单位-单个
	 */
	public java.lang.String getUnit() {
		return getStr("Unit");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String Remark) {
		set("Remark", Remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("Remark");
	}

	/**
	 * 零售价
	 */
	public void setRetailPrice(java.math.BigDecimal RetailPrice) {
		set("RetailPrice", RetailPrice);
	}
	
	/**
	 * 零售价
	 */
	public java.math.BigDecimal getRetailPrice() {
		return get("RetailPrice");
	}

	/**
	 * 最低售价
	 */
	public void setLowPrice(java.math.BigDecimal LowPrice) {
		set("LowPrice", LowPrice);
	}
	
	/**
	 * 最低售价
	 */
	public java.math.BigDecimal getLowPrice() {
		return get("LowPrice");
	}

	/**
	 * 预设售价一
	 */
	public void setPresetPriceOne(java.math.BigDecimal PresetPriceOne) {
		set("PresetPriceOne", PresetPriceOne);
	}
	
	/**
	 * 预设售价一
	 */
	public java.math.BigDecimal getPresetPriceOne() {
		return get("PresetPriceOne");
	}

	/**
	 * 预设售价二
	 */
	public void setPresetPriceTwo(java.math.BigDecimal PresetPriceTwo) {
		set("PresetPriceTwo", PresetPriceTwo);
	}
	
	/**
	 * 预设售价二
	 */
	public java.math.BigDecimal getPresetPriceTwo() {
		return get("PresetPriceTwo");
	}

	/**
	 * 计量单位Id
	 */
	public void setUnitId(java.lang.Long UnitId) {
		set("UnitId", UnitId);
	}
	
	/**
	 * 计量单位Id
	 */
	public java.lang.Long getUnitId() {
		return getLong("UnitId");
	}

	/**
	 * 首选出库单位
	 */
	public void setFirstOutUnit(java.lang.String FirstOutUnit) {
		set("FirstOutUnit", FirstOutUnit);
	}
	
	/**
	 * 首选出库单位
	 */
	public java.lang.String getFirstOutUnit() {
		return getStr("FirstOutUnit");
	}

	/**
	 * 首选入库单位
	 */
	public void setFirstInUnit(java.lang.String FirstInUnit) {
		set("FirstInUnit", FirstInUnit);
	}
	
	/**
	 * 首选入库单位
	 */
	public java.lang.String getFirstInUnit() {
		return getStr("FirstInUnit");
	}

	/**
	 * 价格策略
	 */
	public void setPriceStrategy(java.lang.String PriceStrategy) {
		set("PriceStrategy", PriceStrategy);
	}
	
	/**
	 * 价格策略
	 */
	public java.lang.String getPriceStrategy() {
		return getStr("PriceStrategy");
	}

	/**
	 * 启用 0-禁用  1-启用
	 */
	public void setEnabled(java.lang.Boolean Enabled) {
		set("Enabled", Enabled);
	}
	
	/**
	 * 启用 0-禁用  1-启用
	 */
	public java.lang.Boolean getEnabled() {
		return get("Enabled");
	}

	/**
	 * 自定义1
	 */
	public void setOtherField1(java.lang.String OtherField1) {
		set("OtherField1", OtherField1);
	}
	
	/**
	 * 自定义1
	 */
	public java.lang.String getOtherField1() {
		return getStr("OtherField1");
	}

	/**
	 * 自定义2
	 */
	public void setOtherField2(java.lang.String OtherField2) {
		set("OtherField2", OtherField2);
	}
	
	/**
	 * 自定义2
	 */
	public java.lang.String getOtherField2() {
		return getStr("OtherField2");
	}

	/**
	 * 自定义3
	 */
	public void setOtherField3(java.lang.String OtherField3) {
		set("OtherField3", OtherField3);
	}
	
	/**
	 * 自定义3
	 */
	public java.lang.String getOtherField3() {
		return getStr("OtherField3");
	}

	/**
	 * 是否开启序列号，0否，1是
	 */
	public void setEnableSerialNumber(java.lang.String enableSerialNumber) {
		set("enableSerialNumber", enableSerialNumber);
	}
	
	/**
	 * 是否开启序列号，0否，1是
	 */
	public java.lang.String getEnableSerialNumber() {
		return getStr("enableSerialNumber");
	}

	/**
	 * 租户id
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 租户id
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}

	/**
	 * 删除标记，0未删除，1删除
	 */
	public void setDeleteFlag(java.lang.String deleteFlag) {
		set("delete_Flag", deleteFlag);
	}
	
	/**
	 * 删除标记，0未删除，1删除
	 */
	public java.lang.String getDeleteFlag() {
		return getStr("delete_Flag");
	}

}
