package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMaterialStock<M extends BaseMaterialStock<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 产品id
	 */
	public void setMaterialId(java.lang.Long materialId) {
		set("material_id", materialId);
	}
	
	/**
	 * 产品id
	 */
	public java.lang.Long getMaterialId() {
		return getLong("material_id");
	}

	/**
	 * 仓库id
	 */
	public void setDepotId(java.lang.Long depotId) {
		set("depot_id", depotId);
	}
	
	/**
	 * 仓库id
	 */
	public java.lang.Long getDepotId() {
		return getLong("depot_id");
	}

	/**
	 * 初始库存数量
	 */
	public void setNumber(java.math.BigDecimal number) {
		set("number", number);
	}
	
	/**
	 * 初始库存数量
	 */
	public java.math.BigDecimal getNumber() {
		return get("number");
	}

	/**
	 * 租户id
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 租户id
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}

	/**
	 * 删除标记，0未删除，1删除
	 */
	public void setDeleteFag(java.lang.String deleteFag) {
		set("delete_fag", deleteFag);
	}
	
	/**
	 * 删除标记，0未删除，1删除
	 */
	public java.lang.String getDeleteFag() {
		return getStr("delete_fag");
	}

}
