package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSequence<M extends BaseSequence<M>> extends Model<M> implements IBean {

	/**
	 * 序列名称
	 */
	public void setSeqName(java.lang.String seqName) {
		set("seq_name", seqName);
	}
	
	/**
	 * 序列名称
	 */
	public java.lang.String getSeqName() {
		return getStr("seq_name");
	}

	/**
	 * 最小值
	 */
	public void setMinValue(java.lang.Long minValue) {
		set("min_value", minValue);
	}
	
	/**
	 * 最小值
	 */
	public java.lang.Long getMinValue() {
		return getLong("min_value");
	}

	/**
	 * 最大值
	 */
	public void setMaxValue(java.lang.Long maxValue) {
		set("max_value", maxValue);
	}
	
	/**
	 * 最大值
	 */
	public java.lang.Long getMaxValue() {
		return getLong("max_value");
	}

	/**
	 * 当前值
	 */
	public void setCurrentVal(java.lang.Long currentVal) {
		set("current_val", currentVal);
	}
	
	/**
	 * 当前值
	 */
	public java.lang.Long getCurrentVal() {
		return getLong("current_val");
	}

	/**
	 * 增长步数
	 */
	public void setIncrementVal(java.lang.Integer incrementVal) {
		set("increment_val", incrementVal);
	}
	
	/**
	 * 增长步数
	 */
	public java.lang.Integer getIncrementVal() {
		return getInt("increment_val");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
