package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("jsh_account", "Id", Account.class);
		arp.addMapping("jsh_accounthead", "Id", Accounthead.class);
		arp.addMapping("jsh_accountitem", "Id", Accountitem.class);
		arp.addMapping("jsh_depot", "id", Depot.class);
		arp.addMapping("jsh_depothead", "Id", Depothead.class);
		arp.addMapping("jsh_depotitem", "Id", Depotitem.class);
		arp.addMapping("jsh_functions", "Id", Functions.class);
		arp.addMapping("jsh_inoutitem", "Id", Inoutitem.class);
		arp.addMapping("jsh_log", "id", Log.class);
		arp.addMapping("jsh_material", "Id", Material.class);
		arp.addMapping("jsh_material_stock", "id", MaterialStock.class);
		arp.addMapping("jsh_materialcategory", "Id", Materialcategory.class);
		arp.addMapping("jsh_materialproperty", "id", Materialproperty.class);
		arp.addMapping("jsh_msg", "id", Msg.class);
		arp.addMapping("jsh_orga_user_rel", "id", OrgaUserRel.class);
		arp.addMapping("jsh_organization", "id", Organization.class);
		arp.addMapping("jsh_person", "Id", Person.class);
		arp.addMapping("jsh_role", "Id", Role.class);
		arp.addMapping("jsh_sequence", "seq_name", Sequence.class);
		arp.addMapping("jsh_serial_number", "id", SerialNumber.class);
		arp.addMapping("jsh_supplier", "id", Supplier.class);
		arp.addMapping("jsh_systemconfig", "id", Systemconfig.class);
		arp.addMapping("jsh_tenant", "id", Tenant.class);
		arp.addMapping("jsh_unit", "id", Unit.class);
		arp.addMapping("jsh_user", "id", User.class);
		arp.addMapping("jsh_userbusiness", "Id", Userbusiness.class);
	}
}

