package com.demo.common.model;

import com.demo.common.model.base.BaseAccountitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Accountitem extends BaseAccountitem<Accountitem> {
	
}
