package com.demo.common.model;

import com.demo.common.model.base.BaseAccounthead;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Accounthead extends BaseAccounthead<Accounthead> {
	
}
