package com.demo.common.model;

import com.demo.common.model.base.BaseDepothead;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Depothead extends BaseDepothead<Depothead> {


    private String projectName;

    private String organName;

    private String handsPersonName;

    private String accountName;

    private String allocationProjectName;

    private String materialsList;

    private String opertimeStr;

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public String getOrganName() {
        return organName;
    }

    public void setOrganName(String organName) {
        this.organName = organName;
    }

    public String getHandsPersonName() {
        return handsPersonName;
    }

    public void setHandsPersonName(String handsPersonName) {
        this.handsPersonName = handsPersonName;
    }

    public String getAccountName() {
        return accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    public String getAllocationProjectName() {
        return allocationProjectName;
    }

    public void setAllocationProjectName(String allocationProjectName) {
        this.allocationProjectName = allocationProjectName;
    }

    public String getMaterialsList() {
        return materialsList;
    }

    public void setMaterialsList(String materialsList) {
        this.materialsList = materialsList;
    }

    public String getOpertimeStr() {
        return opertimeStr;
    }

    public void setOpertimeStr(String opertimeStr) {
        this.opertimeStr = opertimeStr;
    }
}
