package com.demo.common.model;

import com.demo.common.model.base.BaseDepotitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Depotitem extends BaseDepotitem<Depotitem> {
	
}
