package com.demo.common.model;

import com.demo.common.model.base.BaseFunctions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Functions extends BaseFunctions<Functions> {
	
}
