package com.demo.common.model;

import com.demo.common.model.base.BaseInoutitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Inoutitem extends BaseInoutitem<Inoutitem> {
	
}
