package com.demo.common.model;

import com.demo.common.model.base.BaseMaterialStock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialStock extends BaseMaterialStock<MaterialStock> {
	
}
