package com.demo.common.model;

import com.demo.common.model.base.BaseMaterialcategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Materialcategory extends BaseMaterialcategory<Materialcategory> {
	
}
