package com.demo.common.model;

import com.demo.common.model.base.BaseMaterial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Material extends BaseMaterial<Material> {
	
}
