package com.demo.common.model;

import com.demo.common.model.base.BaseMaterialproperty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Materialproperty extends BaseMaterialproperty<Materialproperty> {
	
}
