package com.demo.common.model;

import com.demo.common.model.base.BaseOrgaUserRel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrgaUserRel extends BaseOrgaUserRel<OrgaUserRel> {
	
}
