package com.demo.common.model;

import com.demo.common.model.base.BaseOrganization;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Organization extends BaseOrganization<Organization> {
	
}
