package com.demo.common.model;

import com.demo.common.model.base.BaseSequence;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sequence extends BaseSequence<Sequence> {
	
}
