package com.demo.common.model;

import com.demo.common.model.base.BaseSerialNumber;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SerialNumber extends BaseSerialNumber<SerialNumber> {
	
}
