package com.demo.common.model;

import com.demo.common.model.base.BaseSystemconfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Systemconfig extends BaseSystemconfig<Systemconfig> {
	
}
