package com.demo.common.model;

import com.demo.common.model.base.BaseUserbusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userbusiness extends BaseUserbusiness<Userbusiness> {
	
}
