package com.jsh.erp.datasource.mappers;

import com.jsh.erp.datasource.entities.UserPerson;
import com.jsh.erp.datasource.entities.UserPersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userperson
     *
     * @mbggenerated
     */
    int countByExample(UserPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userperson
     *
     * @mbggenerated
     */
    int deleteByExample(UserPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userperson
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userperson
     *
     * @mbggenerated
     */
    int insert(UserPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userperson
     *
     * @mbggenerated
     */
    int insertSelective(UserPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userperson
     *
     * @mbggenerated
     */
    List<UserPerson> selectByExample(UserPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userperson
     *
     * @mbggenerated
     */
    UserPerson selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userperson
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserPerson record, @Param("example") UserPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userperson
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserPerson record, @Param("example") UserPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userperson
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userperson
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserPerson record);
}